config/routes.rb
Rails.application.routes.draw do

  resources :logins

  resources :users

  resources :carts

  resources :products
  
  resources :users  do
    resources :carts
  end

  root 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  def self.user_cart_sum(params)
    carts = Cart.where(user_id: params[:user_id])
    sum = 0
    carts.each { |cart| sum += cart.product.price * cart.count}
    (sum * 1.08).to_i
  end

  def self.user_cart_fare(params)
    if params[:sum] >= 2000
      0
    else
      500
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :carts
  validates_presence_of :name, :price
  validates_numericality_of :price, greater_than: 0, allow_blank: true
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentPresenceValidator, :attributes => :avatar
  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes
end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
  has_many :carts
  before_save :encrypt_password
  validates_uniqueness_of :name
  def encrypt_password
    if self.password.present?
      self.password = Digest::SHA1.hexdigest(self.password)
    else
      self.password = self.password_was
    end
  end

  def registered?
    u = User.find_by(name: self.name, password: Digest::SHA1.hexdigest(self.password))
    if u != nil
      self.id = u.id
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /carts
  # GET /carts.json
  def index
    if params[:user_id] != nil
      @carts = Cart.where(user_id: params[:user_id])
      @cart_sum = Cart.user_cart_sum(user_id: params[:user_id])
      @cart_fare = Cart.user_cart_fare(sum: @cart_sum)
    else
      @carts = Cart.all
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new(count: 1)
    @product_selector = Product.all.collect {|p| [p.name, p.id]}
  end

  # GET /carts/1/edit
  def edit
    @product_selector = Product.all.collect {|p| [p.name, p.id]}
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    @cart.user_id = session[:login]
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to user_carts_path(user_id: session[:login]), notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:name,:count,:product_id,:user_id)
    end
    
    def require_login
      if session[:login] == nil
        redirect_to new_login_path
      end
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    if session[:login] != nil
      redirect_to products_path
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.registered?
      session[:login] = @user.id
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    session[:login] = nil
    redirect_to products_path
  end

  private
    def user_params
      params.require(:user).permit(:name,:password)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :photo, :price, :description, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if show_product_select %>
    <div class="field">
      <%= f.label :商品 %><br>
      <%= f.select :product_id, @product_selector%>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :数量 %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/carts/_form_new.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :商品 %><br>
    <%= f.select :product_id, @product_names%>
  </div>

  <div class="field">
    <%= f.label :数量 %><br>
    <%= f.number_field :sum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>数量变更</h1>

<%= @cart.product.name %>
<%= @cart.count %>
<%= render partial:'form', locals: {show_product_select: true} %>


<%= link_to '戻る', carts_path %>

app/views/carts/index.html.erb
<h1>ショッピングカート</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th colspan="1"></th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= image_tag(cart.product.avatar.url(:thumb)) %></td>
        <td><%= cart.product.name %></td>
        <td><%= cart.count %></td>
        <!-- <td><%= link_to 'Show', cart %></td> -->
        <td><%= link_to '数量变更', edit_cart_path(cart) %></td>
        <td><%= link_to '削除', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3><%= "sum: " + @cart_sum.to_s %></h3>
<h3><%= "fare: " + @cart_fare.to_s %></h3><br>

<%= link_to 'メニューに戻る', products_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render partial:'form', locals: {show_product_select: true} %>

<%= link_to '戻る', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cart.name %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', user_carts_path(user_id: session[:login]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if session[:login] != nil %>
<div class="cartbar">
  <td><%= link_to "カート表示", user_carts_path(user_id: session[:login]) %></td>
  <td><%= link_to "カートに追加", new_user_cart_path(user_id: session[:login]) %></td>
  <td><%= link_to "logout", login_path(id: session[:login]), method: :delete %></td>
</div>
<% else %>
<div class="cartbar">
  <td><%= link_to "登録", new_login_path %></td>
</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/destroy.html.erb
<h1>Logins#destroy</h1>
<p>Find me in app/views/logins/destroy.html.erb</p>

app/views/logins/new.html.erb
<h1>Login</h1>
<%= form_for(@user, :url=>logins_path)  do |f|%>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit :Login %>
  </div>
<% end %>

<%= link_to "新规登録", new_user_path %>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true } ) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>期間・季節・数量限定メニュー </h1>

<div class="contents">
<ul class="menuList">
  <% @products.each do |product| %>
    <li>
      <%= link_to image_tag(product.avatar.url(:thumb)), product %>
      <br>
      <%= link_to product.name, product %>
      <br>
      <%= "¥"+product.price.to_s %>
    </li>
  <% end %>
</ul>
</div>
<br>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<h1>メニュー情報</h1>
<p>
  <%= @product.name %>
</p>

<p>
  <%= "¥" + @product.price.to_s %>
</p>

<p>
  <%= @product.description %>
</p>

<p>
  <%= image_tag(@product.avatar.url(:medium)) %>
</p>

<%= link_to '更新する', edit_product_path(@product) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit :確認　%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>